### ISSUE TITLE
Plugin builds on MacOS arm64, but does not load in VCV Rack 2.6.0 due to manifest issue

### ISSUE THREAD

**Issue by fractalgee** [silver-ag/visions#2]
Hi, I saw you submitted your plugin to the Library and thought to try it before the VCV team gets around to doing the integration testing. You are defining a module in the manifest that is not in the plugin. That causes the whole plugin to fail loading.

Error in VCV Rack log file:

`Could not load plugin /Users/<user>/Library/Application Support/Rack2/plugins-mac-arm64/silver-Visions: Manifest contains module visions-VideoOut but it is not defined in plugin`

**Comment by silver-ag** [comment]
oh thanks! i suspect it's because i changed the module slugs. i've changed them back, but i'm not sure if that's it because it was working for me anyway (linux x86/64, 2.5.2 and 2.6.0).

**Comment by fractalgee** [comment]
OK, I repulled and rebuilt and it's now loading. Have to spend some time with it later this evening.
